"""Behaviour tests for the P03 family extraction, linkage and cost estimation.

The invariants that matter: an ancestor slot is only filled from an explicit CBDB
kin id, fuzzy matches never become decisions, biography detection does not mistake a
mere mention for a 傳, and the cost estimate's arithmetic follows the published
DeepSeek prices.
"""

from __future__ import annotations

import pandas as pd
import pytest

from qing_elite.build_family import assemble_family, scenario_person_counts
from qing_elite.family.kinship import (
    _code_rank,
    _evidence_origin,
    _rewrite_id,
    _slot_for_code,
)
from qing_elite.linkage.candidates import CANDIDATE_STATUS, RecallConfig, recall_candidates
from qing_elite.cgedq.officials import degree_lookup, load_chushen_recodes
from qing_elite.utils.config import RAW_DIR, load_offices
from qing_elite.llm.estimation import (
    PRICES_CNY_PER_MTOK,
    extract_person_section,
    family_window,
    estimate_tokens,
    _looks_like_person,
)


# --------------------------------------------------------------- kinship slots


def test_slot_codes_cover_variants_but_prefer_the_primary_code() -> None:
    assert _slot_for_code(75) == "father"
    assert _slot_for_code(82) == "father"  # 嗣父 is still a father slot
    assert _slot_for_code(62) == "grandfather"
    assert _slot_for_code(48) == "great_grandfather"
    assert _slot_for_code(180) is None  # 子 is not an ancestor slot
    assert _code_rank("father", 75) < _code_rank("father", 82)


def test_merged_person_ids_are_rewritten_to_the_survivor() -> None:
    merged = {98561: 31}
    assert _rewrite_id(98561, merged) == 31
    assert _rewrite_id(42, merged) == 42
    assert _rewrite_id(None, merged) is None


def test_evidence_origin_separates_cited_from_autogenerated() -> None:
    assert _evidence_origin(4763, None) == "source_cited"
    assert _evidence_origin(0, "Auto-generated from PersonID = 1") == "autogenerated_only"
    assert _evidence_origin(0, None) == "unattributed"
    assert _evidence_origin(12, "auto") == "source_cited_autogenerated"


# ------------------------------------------------------------ family assembly


def _master_frame() -> pd.DataFrame:
    return pd.DataFrame(
        [
            {
                "person_uid": "cbdb:1",
                "cbdb_personid": 1,
                "cgedq_person_id": None,
                "source": "CBDB",
                "tiers_present": "A1|B",
                "highest_tier": "A1",
                "c_name_chn": "甲",
                "native_province_effective": "安徽",
                "banner_effective": "unknown",
                "degree_effective": "進士",
                "linkage_confidence": None,
            },
            {
                "person_uid": "cgedq:N9",
                "cbdb_personid": None,
                "cgedq_person_id": "N9",
                "source": "CGEDQ",
                "tiers_present": "D",
                "highest_tier": "D",
                "c_name_chn": "乙",
                "native_province_effective": "山東",
                "banner_effective": "unknown",
                "degree_effective": "舉人",
                "linkage_confidence": "unmatched",
            },
        ]
    )


def test_missing_slots_are_explicit_rows_not_absent_rows() -> None:
    relations = pd.DataFrame(
        [
            {
                "cbdb_personid": 1,
                "slot": "father",
                "kin_code": 75,
                "kin_relation_chn": "父",
                "ancestor_personid": 2,
                "ancestor_personid_raw": 2,
                "remapped_from_merged_id": False,
                "evidence_origin": "source_cited",
                "source_textid": 10,
                "source_title": "某書",
                "source_pages": "1",
                "source_notes": None,
                "n_candidate_codes": 1,
                "kin_code_primary": True,
            }
        ]
    )
    attributes = pd.DataFrame(
        [
            {
                "ancestor_personid": 2,
                "ancestor_name": "父甲",
                "ancestor_degree": "進士",
                "ancestor_n_postings": 3,
                "ancestor_native_addr": "桐城",
            }
        ]
    )
    family = assemble_family(_master_frame(), relations, attributes)
    assert len(family) == 6  # 2 persons x 3 slots, including CGED-Q-only persons
    father = family[(family["person_uid"] == "cbdb:1") & (family["ancestor_slot"] == "father")].iloc[0]
    assert father["ancestor_known"]
    assert father["match_method"] == "explicit_kin_id"
    assert father["match_status"] == "confirmed_by_explicit_kin_id"
    assert father["match_score"] == 1.0
    assert father["ancestor_name"] == "父甲"
    assert not father["llm_needed"]
    unknown = family[(family["person_uid"] == "cgedq:N9") & (family["ancestor_slot"] == "father")].iloc[0]
    assert not unknown["ancestor_known"]
    assert unknown["llm_needed"]
    assert unknown["match_status"] == "not_in_cbdb_structured_data"
    assert pd.isna(unknown["match_score"])


def test_scenario_counts_are_person_level_not_tier_level() -> None:
    family = pd.DataFrame(
        [
            {"person_uid": "cbdb:1", "llm_needed": True, "tiers_present": "A1|B", "linkage_confidence": None},
            {"person_uid": "cbdb:2", "llm_needed": False, "tiers_present": "A1", "linkage_confidence": None},
            {"person_uid": "cbdb:3", "llm_needed": True, "tiers_present": "D", "linkage_confidence": "high"},
            {"person_uid": "cgedq:N1", "llm_needed": True, "tiers_present": "D", "linkage_confidence": "unmatched"},
        ]
    )
    counts = scenario_person_counts(family, pd.DataFrame())
    assert counts["S1_full_universe"] == 3  # every person with a gap, counted once
    assert counts["S2_ABC_all_tiers"] == 1
    assert counts["S4_ABC_excluding_D_persons"] == 1
    assert counts["S3_ABC_plus_D_high_linkage"] == 2  # ABC gaps + high-confidence D


# ------------------------------------------------------------------- degrees

RECODES = RAW_DIR / "cgeq" / "cgedq_jsl_chushen_recodes.tab"


@pytest.mark.skipif(not RECODES.exists(), reason="CGED-Q release not present")
def test_jsl_degree_lookup_uses_the_declared_ladder() -> None:
    """Regression: the released chushen_order column is textual, not numeric.

    Parsing it as a number silently produced an empty lookup, so every JSL degree
    came back unknown.
    """
    recodes = load_chushen_recodes(RECODES)
    lookup = degree_lookup(recodes, load_offices()["cgedq"]["degree_category_rank"])
    assert len(lookup) > 50
    assert lookup["進士"] == ("進士", 6)
    assert lookup["舉人"][1] == 5
    assert lookup["監生"][1] == 3
    assert lookup["蔭生"][1] == 3
    assert lookup["生員"][1] == 2
    assert load_offices()["cgedq"]["degree_category_rank"]["空白"] == 0
    raw_values = set(recodes["出身一"].dropna())
    assert all(value in lookup for value in raw_values)


# ------------------------------------------------------------- text handling


def test_family_window_merges_and_caps() -> None:
    # A single keyword yields its own +/- radius window (no padding).
    single = family_window("甲" * 400 + "父" + "乙" * 400, radius=100, max_chars=500)
    assert len(single) == 200
    assert "父" in single
    # Overlapping windows merge, then the whole thing is capped.
    merged = family_window("父" + "甲" * 400 + "祖" + "甲" * 400 + "曾祖" + "甲" * 400, radius=1000, max_chars=500)
    assert len(merged) == 500
    assert family_window("沒有關鍵詞", radius=10, max_chars=4) == "沒有關鍵"


def test_biography_detection_requires_a_real_entry() -> None:
    volume = "== 張廷玉 ==\n張廷玉，字衡臣，安徽桐城人。" + "文" * 200 + "\n== 鄂爾泰 ==\n鄂爾泰，字毅庵。" + "文" * 200
    assert extract_person_section(volume, "張廷玉").startswith("張廷玉，字衡臣")
    assert extract_person_section(volume, "鄂爾泰").startswith("鄂爾泰")
    # An 藝文志 style mention must not be mistaken for a biography.
    mention_only = "書目。張廷玉撰。" + "文" * 500
    assert extract_person_section(mention_only, "張廷玉") == ""


def test_biography_detection_accepts_the_other_heading_level() -> None:
    volume = "=李鶴年=\n李鶴年，字子和，奉天義州人。" + "文" * 200
    assert extract_person_section(volume, "李鶴年").startswith("李鶴年")


@pytest.mark.parametrize("heading", ["列傳七十五", "【論】", "本紀一", "二十一年"])
def test_heading_filter_rejects_non_people(heading: str) -> None:
    assert not _looks_like_person(heading)


# --------------------------------------------------------------- cost model


def test_cost_estimate_follows_published_prices() -> None:
    estimate = estimate_tokens(
        1000,
        [1000] * 10,
        output_template="x" * 500,
        tokens_per_char=0.6,
        prompt_overhead_tokens=400,
    )
    # 1000 chars x 0.6 + 400 overhead = 1000 input tokens per person
    assert estimate.mean_input_tokens == 1000.0
    assert estimate.total_input_tokens == 1_000_000.0
    assert estimate.total_output_tokens == 300_000.0
    off_peak = PRICES_CNY_PER_MTOK["off_peak"]
    expected = 1.0 * off_peak["input_cache_miss"] + 0.3 * off_peak["output"]
    assert estimate.rmb_off_peak == pytest.approx(round(expected, 2))
    assert estimate.rmb_peak > estimate.rmb_off_peak


# ---------------------------------------------------------------- linkage


def test_fuzzy_recall_only_proposes_candidates() -> None:
    subjects = pd.DataFrame(
        [
            {"cgedq_person_id": "N1", "name_norm": "張廷玉", "native_province": "安徽", "degree_effective": "進士"},
            {"cgedq_person_id": "N2", "name_norm": "完全不像", "native_province": None, "degree_effective": None},
        ]
    )
    candidates = pd.DataFrame(
        [
            {"cbdb_personid": 10, "name_norm": "張廷玉", "cbdb_province": "安徽", "degree_cbdb": "進士"},
            {"cbdb_personid": 11, "name_norm": "張廷玉", "cbdb_province": "江蘇", "degree_cbdb": None},
        ]
    )
    recall = recall_candidates(subjects, candidates, config=RecallConfig(limit=3, score_cutoff=82.0))
    assert set(recall["match_status"]) == {CANDIDATE_STATUS}
    assert "accepted" not in set(recall["match_status"])
    assert set(recall["subject_id"]) == {"N1"}  # the unrelated subject gets no proposal
    assert len(recall) == 2  # both same-name candidates survive
    assert "province=match" in recall.set_index("candidate_cbdb_personid").at[10, "match_features"]
    assert recall["match_score"].min() == 100.0
